server:
  port: 7475
spring:
  acrive:
    profile: local
---
spring:
  profile: local
  application:
    name: order
    
  ## Spring Data Source
  ## 읽은 후 바꿔야 할 것은
  ## datasource.platform, datasource.url, database.username, database.password, database.driver-class-name
  ## jpa.hibernate.ddl-auto, jpa-properties.hibernate.dialect 
  datasource:
    platform: h2
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false

##mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: tqa.demo.order.entity, tqa.demo.order.dto
          
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        loggerLevel: FULL
        connectTimeout: 100000
        readTimeout: 10000
                  
member:
    service:
        url: http://localhost:7575

external:
  services:
    -
      name: product
      url: http://localhost:7575
    -
      name: local
      url: http://localhost:9001 
      
framework:
      domain:
        enabled: true
        services:
          - name: local
            url: http://localhost:7776
          - name: product
            url: http://localhost:8887
      apim-consumer:
        enabled: true
        endpoint-url: https://devapi.framework.co.kr:443/framework/userid

      http-client:
        enabled: true